### ISSUE TITLE
Move glennrp/libpng into this organization

### ISSUE THREAD

**Issue by Neustradamus** [pnggroup/libpng-see-issue-2#2]
@ctruta, @glennrp: Can you transfer https://github.com/glennrp/libpng into this organization?

Same for https://github.com/glennrp/libpng-releases.

Linked to:
- https://github.com/glennrp/libpng/issues/385

**Comment by ctruta** [comment]
Important Update:

GitHub has just reached out to me. They are willing to transfer the ownership of Glenn's repository to our group. (Yaaay, GitHub!)

**Comment by ctruta** [comment]
Thank you @github!

**Comment by Neustradamus** [comment]
Dear @pnggroup team members, @ctruta,

In the right menu, you have the button to transfer this issue in the good repository, can you do it?
- https://github.com/pnggroup/libpng

It takes 10s to do it.

After the transfer of all issues, this repository can be removed.

Thanks in advance.

cc: @svgeesus, @groelofs.
