### ISSUE TITLE
Library name changed unintentionally?

### ISSUE THREAD

**Issue by dlemstra** [pnggroup/libpng-see-issue-2#3]
Commit 70fda18 changed the library name from `libpng16.a` to `png16.a`. 

Before this commit:
```
[ 92%] Building C object CMakeFiles/png_static.dir/intel/filter_sse2_intrinsics.c.o
[ 93%] Linking C static library libpng16.a
[100%] Built target png_static
```

After this commit:
```
[ 92%] Building C object CMakeFiles/png_static.dir/intel/filter_sse2_intrinsics.c.o
[ 93%] Linking C static library png16.a
[100%] Built target png_static
```

This broke the oss-fuzz build of ImageMagick that uses `cmake` to build this library. I don't think the library name can just be changed?

**Comment by ctruta** [comment]
Not intentionally. I haven't noticed it myself, and it was already reported, but thank you for pinging us anyway.
I will fix it.

**Comment by ctruta** [comment]
I reverted the offending commit, for now.

**Comment by dlemstra** [comment]
Thanks for the quick fix.

**Comment by Neustradamus** [comment]
Dear @pnggroup team members, @ctruta,

In the right menu, you have the button to transfer this issue in the good repository, can you do it?
- https://github.com/pnggroup/libpng

It takes 10s to do it.

After the transfer of all issues, this repository can be removed.

Thanks in advance.

cc: @svgeesus, @groelofs.
